version: '3'

volumes:
  frontend:

networks:
  fullnet: 

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fullnet
    ports:
      - 80:80
    container_name: ngx

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/home/backend
    networks:
      - fullnet
    ports:
      - 8000
    container_name: backend
    command: --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    volumes:
      - frontend:/usr/src/app/node_modules
      - ./frontend:/usr/src/app
    networks:
      - fullnet
    ports:
      - 3000
    container_name: frontend
