version: '3'

volumes:
  frontend:

networks:
  web_server: 

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/home/backend
    networks:
      - web_server
    ports:
      - 8000:8000
    command: --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    volumes:
      - frontend:/usr/src/app/node_modules
      - ./frontend:/usr/src/app
    networks:
      - web_server
    ports:
      - 3000:3000

